### ISSUE TITLE
Render functions in layouts aren't re-processed through WebC

### ISSUE THREAD

**Issue by darthmall** [11ty/eleventy-plugin-webc#20]
If you use WebC for a layout, and have a render function that writes out another WebC component, the WebC component is not processed by WebC.

If you do the same thing in a page template, however, it works.

I've created a repo to reproduce the issue: https://github.com/darthmall/11ty-webc-render-function-layout-bug

**Comment by zachleat** [comment]
This will require https://github.com/11ty/webc/issues/51

I think we want to encourage folks to use `@raw` in layout templates instead of `@html` so that we can re-enable reprocessing mode in Layouts https://github.com/11ty/eleventy-plugin-webc/blob/cc118905bd9ba8f8d5e1154a6d9947789d355c38/src/incremental.js#L29
